config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get 'search' => 'search#search'


  resources :users,only: [:show,:index,:edit,:update] do
    get 'users/follower' => 'users#follower'
    get 'users/followed' => 'users#followed'
  end

  resources :books,only: [:index,:show,:create,:update,:edit,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  # ひょろわ〜機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  # フォロー取得 一行目は、ユーザーとフォローする人を結びつけています。
  # フォロワー取得 二行目は、ユーザーとフォローされる人を結びつけています。

  # 3行目 ユーザーは多くのフォローしているユーザーがいて、自分はfollower、相手はfollowed
  # 4行目 ユーザーは多くのフォローされているユーザーがいて、自分はfollowed、相手はfollower
  # follower n<--->1 User 1<-->n followed

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  # フォローしていればtureを返す
  def following?(user)
    following_user.include?(user)
  end


  def User.search(word,how_method)
    if how_method == "forward_match"
      User.where("name LIKE ?","#{word}%")
    elsif how_method == "backward_match"
      User.where("name LIKE ?","%#{word}")
    elsif how_method == "perfect_match"
      User.where("name LIKE ?","#{word}")
    elsif how_method == "partial_match"
      User.where("name LIKE ?","%#{word}%")
    else
      @search = User.all
    end
  end

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, uniqueness: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user.id
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follower
    user = User.find(params[:user_id])
    @users = user.follower
  end

  def followed
    user = User.find(params[:user_id])
    @users = user.followed
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<tr>
		<th>follows</th>
		<th><%= link_to user.follower.count, user_users_follower_path(user.id) %></th>
	</tr>

	<tr>
		<th>followers</th>
		<th><%= link_to user.followed.count, user_users_followed_path(user.id) %></th>
	</tr>
</table>


<% if user === current_user %>
	<div class="row">
		<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% end %>

<% if user != current_user %>
	<% if current_user.following?(user) %>
		<!-- もしログインしているユーザーが、このユーザーをフォロしているなら -->
		<%= link_to 'フォロー外す', unfollow_path(user.id),method: :POST, class: "btn btn-md btn-primary" %>
	<% else %>
		<!-- もしログインしているユーザーが、このユーザーをフォロしていないなら -->
		<%= link_to 'フォローする', follow_path(user.id),method: :POST, class: "btn btn-md btn-success" %>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/followed.html.erb
<div class="row">
<div class="col-xs-12">
  <h2>Followed Users</h2>

  <table class="table">

    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user.follower, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.follower.name %></td>
        <td><p>フォロー数 : <%= user.follower.follower.count %></p></td>
        <td><p>フォロワー数 : <%= user.follower.followed.count %></p></td>
        <td><%= link_to "Show", user_path(user.follower.id), class: "user_#{user.id}" %></td>
      </tr>
      <% end %>
    </tbody>

  </table>
</div>
</div>

app/views/users/follower.html.erb
<div class="row">
<div class="col-xs-12">
  <h2>Follower Users</h2>

  <table class="table">

    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user.followed, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.followed.name %></td>
        <td><p>フォロー数 : <%= user.followed.follower.count %></p></td>
        <td><p>フォロワー数 : <%= user.followed.followed.count %></p></td>
        <td><%= link_to "Show", user_path(user.followed.id), class: "user_#{user.id}" %></td>
      </tr>
      <% end %>
    </tbody>

  </table>
</div>
</div>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>
	<div class="col-xs-9">

		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg" %></td>
					<td><%= user.name %></td>
					<td>
						<p>フォロー数: <%= user.follower.count %></p>
					</td>
					<td>
						<p>フォロワー数: <%= user.followed.count %></p>
					</td>
					<td>
						<% if user != current_user %>
							<% if current_user.following?(user) %>
								<!-- もしログインしているユーザーが、このユーザーをフォロしているなら -->
								<%= link_to 'フォロー外す', unfollow_path(user.id),method: :POST %>
							<% else %>
								<!-- もしログインしているユーザーが、このユーザーをフォロしていないなら -->
								<%= link_to 'フォローする', follow_path(user.id),method: :POST %>
							<% end %>
						<% end %>
					</td>
					<td><%= link_to "Show", user_path(user.id), class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>