config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get 'search' => 'search#search'


  resources :users,only: [:show,:index,:edit,:update] do
    get 'users/follower' => 'users#follower'
    get 'users/followed' => 'users#followed'
  end

  resources :books,only: [:index,:show,:create,:update,:edit,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end


end

app/models/book.rb
class Book < ApplicationRecord

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
	  favorites.where(user_id: user.id).exists?
	end

	def Book.search(word,how_method)
		if how_method == "forward_match"
			Book.where("title LIKE ?","#{word}%")
		elsif how_method == "backward_match"
			Book.where("title LIKE ?","%#{word}")
		elsif how_method == "perfect_match"
			Book.where("title LIKE ?","#{word}")
		elsif how_method == "partial_match"
			Book.where("title LIKE ?","%#{word}%")
		else
			Book.all
		end
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comments.html.erb
<li class="user-comments">
  <div class="image">
    <%= attachment_image_tag(book_comment.user, :profile_image, size: '50x50', fallback: "no-image.jpg") %>
    <%= book_comment.user.name %>
  </div>
  <div class="comment-text">
    <%= book_comment.comment %>
  </div>
  <% if book_comment.user == current_user %>
    <div>
      <%= link_to "Delete", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
    </div>
  <% end %>
</li>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
  <i class="fas fa-heart" aria-hidden="true"></i>
  <%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
  <i class="far fa-heart" aria-hidden="true"></i>
  <%= book.favorites.count %>
  <% end %>
<% end %>

<!--
いいねボタンのlink_toにremote: trueを追加します。
通常であれば、link_toで呼ばれるアクションに対応するhtml.erbファイルを呼び出すところ、
js.erbファイルを呼び出せるようになります。
ページ遷移を行わず非同期で通信が行われるようになります。
 -->

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_post_comments.html.erb
  <% book_comments.each do |book_comment| %>
  <!-- コメントのテンプレ化 -->
    <%= render 'books/comments', book_comment: book_comment %>
  <% end %>

<%= form_with model: [book,book_comment], remote: true do |f| %>
    <div class="col-sm-2">
      <%= f.text_area :comment, rows:'5', placeholder: "コメント...", class: "text_box" %>
      <%= f.submit "送信", class: "btn btn-md btn-success" %>
    </div>

<% end %>

app/views/books/_posts.html.erb
<tr>
  <td>
    <%= link_to user_path(book.user) do %>
    <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
    <% end %>
  </td>
  <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
  <td><%= book.body %></td>
  <td id="like-<%= book.id %>">
    <!-- idとして、book.idを含めたid名をつける -->
    <%= render 'books/favorite', book: book %>
    <!--　ファボのテンプレート化 -->
  </td>
  <td>
    <p>コメント数: <%= book.book_comments.count %></p>
  </td>
</tr>

<!-- -->

app/views/books/edit.html.erb
<% if @book.errors.any? %>
	<div id="error_explanation">
		<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3><
		<ul>
			<% @book.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>


<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div id="error_explanation">
	<h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3><
	<ul>
		<% @book.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<%= render 'books/posts', book: book %>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book_new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<% if @book.user == current_user %>
						<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
					<td id="like-<%= @book.id %>">
						<% if @book.favorited_by?(current_user) %>
							<%= link_to book_favorites_path(@book), method: :delete, remote: true do %>
							<i class="fas fa-heart" aria-hidden="true"></i>
							<%= @book.favorites.count %>
							<% end %>
						<% else %>
							<%= link_to book_favorites_path(@book), method: :post, remote: true do %>
							<i class="far fa-heart" aria-hidden="true"></i>
							<%= @book.favorites.count %>
							<% end %>
						<% end %>
					</td>
					<td>
					<p>コメント数: <%= @book.book_comments.count %></p>
					</td>
				</tr>
			</table>

			<!-- コメント一覧テンプレ化（サブミット含む） -->
			<ol id="comment-<%= @book.id %>">
			<%= render 'books/post_comments', book_comments: @book.book_comments, book: @book, book_comment: @book_comment %>
			</ol>

	</div>
</div>