config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#top'
  get 'home/about' => 'home#about'

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'

  get 'search' => 'search#search'


  resources :users,only: [:show,:index,:edit,:update] do
    get 'users/follower' => 'users#follower'
    get 'users/followed' => 'users#followed'
  end

  resources :books,only: [:index,:show,:create,:update,:edit,:destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
	  favorites.where(user_id: user.id).exists?
	end

	def Book.search(word,how_method)
		if how_method == "forward_match"
			Book.where("title LIKE ?","#{word}%")
		elsif how_method == "backward_match"
			Book.where("title LIKE ?","%#{word}")
		elsif how_method == "perfect_match"
			Book.where("title LIKE ?","#{word}")
		elsif how_method == "partial_match"
			Book.where("title LIKE ?","%#{word}%")
		else
			Book.all
		end
	end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  validates :comment, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  # ひょろわ〜機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  # フォロー取得 一行目は、ユーザーとフォローする人を結びつけています。
  # フォロワー取得 二行目は、ユーザーとフォローされる人を結びつけています。

  # 3行目 ユーザーは多くのフォローしているユーザーがいて、自分はfollower、相手はfollowed
  # 4行目 ユーザーは多くのフォローされているユーザーがいて、自分はfollowed、相手はfollower
  # follower n<--->1 User 1<-->n followed

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  # フォローしていればtureを返す
  def following?(user)
    following_user.include?(user)
  end


  def User.search(word,how_method)
    if how_method == "forward_match"
      User.where("name LIKE ?","#{word}%")
    elsif how_method == "backward_match"
      User.where("name LIKE ?","%#{word}")
    elsif how_method == "perfect_match"
      User.where("name LIKE ?","#{word}")
    elsif how_method == "partial_match"
      User.where("name LIKE ?","%#{word}%")
    else
      @search = User.all
    end
  end

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, presence: true, uniqueness: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(resource.id)
	end

	def after_sign_out_path_for(resource)
  	root_path
	end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def delete
    @book = Book.find(params[:id])
    @book.destoy
    redirect_to books_path
  end

  private

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back(fallback_location: books_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    # favorite = Favorite.find_by(book_id: @book, user_id: current_user.id)
    favorite.destroy
    # redirect_back(fallback_location: books_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  # サーチ機能
  def search
    # プルダウンで選択された値が入るとこ
    @user_or_book = params[:option]
    @how_method = params[:method]
    @word = params[:word]

    #　プルダウンでuserかbookかで、参照するモデルを決める
    if @user_or_book == "user"
      @user = User.search(params[:word],@how_method)
    else
      @book = Book.search(params[:word],@how_method)
    end
    # searchメソッド カッコ内にテキストで入力された値と、選択された方の値を引数としてモデルに送っています。
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update,:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user.id
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follower
    user = User.find(params[:user_id])
    @users = user.follower
  end

  def followed
    user = User.find(params[:user_id])
    @users = user.followed
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--  -->
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
              <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
              <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
              <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
              <li><%= link_to " sign up", new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
              <li><%= link_to " login", new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <!-- 検索機能の記述ここから -->
    <% if user_signed_in? %>

      <div class="container search">
        <%= form_tag(search_path, method: :get) do %>
        <!-- form_tagはDBの変更に関わらない時に使う
          検索フォームでは、検索結果がすぐ表示された方がいいので(当然ですが)、methodはgetにしておきましょう。 -->
          <%= text_field_tag :word %>
          <%= select_tag(:option, options_for_select([["User","user"],["Book","book"]])) %>
          <%= select_tag(:method, options_for_select([["前方一致","forward_match"],["後方一致","backward_match"],["完全一致","perfect_match"],["部分一致","partial_match"]])) %>
          <%= submit_tag 'Search' %>
        <% end %>
      </div>

    <% end %>


    <div class="container">
      <p id="notice"><%= notice %></p>

      <%= yield %>

    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>